# Generated by Django 5.1.1 on 2024-09-19 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comment_content_comment_date_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='No content available'),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
