# Generated by Django 5.1.1 on 2024-09-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_managment_system', '0002_alter_student_email_alter_student_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
